### ISSUE TITLE
Parser - Swagger - Migration TODO

### ISSUE THREAD

**Issue by JonathanMontane** [luckymarmot/API-Flow#38]
### TODO
- [x] Improve support for parameters of type `array`, as they behave very differently from other types
- [x] Improve path parameter support by saving them in environment variables
- [x] Remove `schema` field from `Response`, since it has been moved into parameters

### Potential TODO
- [x] Support `tags` and `operationId` ?
- [x] Support `^x-.*` patterns ?
- [x] Merge `_extractResponseExternals` and `_extractExternals`
- [x] Merge `_extractResponseBodies` and `_extractBodies` -- behaviors are somewhat different, not merged

**Note:** This list will be updated as we progress in the migration

**Comment by JonathanMontane** [comment]
We are now supporting the `^x-` patterns that we generate with our serializer, which should help reduce the quantity of data loss.

**Comment by JonathanMontane** [comment]
implemented in commit [2fba116](https://github.com/luckymarmot/API-Flow/commit/2fba1162960039d0911d7680fca9e19102c10d8b)
